/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica;



/**
 *
 * @author gustavo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cad_veiculo = new javax.swing.JMenuItem();
        cad_ponto = new javax.swing.JMenuItem();
        ferramenta = new javax.swing.JMenu();
        movimento = new javax.swing.JMenuItem();
        estacionamento_proximo = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 153));

        jMenu1.setText("Cadastro");

        cad_veiculo.setText("Veiculo");
        cad_veiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cad_veiculoMouseClicked(evt);
            }
        });
        cad_veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_veiculoActionPerformed(evt);
            }
        });
        jMenu1.add(cad_veiculo);

        cad_ponto.setText("Ponto");
        cad_ponto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cad_pontoMouseClicked(evt);
            }
        });
        cad_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cad_pontoActionPerformed(evt);
            }
        });
        jMenu1.add(cad_ponto);

        jMenuBar1.add(jMenu1);

        ferramenta.setText("Ferramentas");

        movimento.setText("Movimentações");
        movimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movimentoActionPerformed(evt);
            }
        });
        ferramenta.add(movimento);

        estacionamento_proximo.setText("Estacionamentos Proximos");
        estacionamento_proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estacionamento_proximoMouseClicked(evt);
            }
        });
        estacionamento_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionamento_proximoActionPerformed(evt);
            }
        });
        ferramenta.add(estacionamento_proximo);

        jMenuBar1.add(ferramenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cad_veiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cad_veiculoMouseClicked
        CadastroVeiculo c = new CadastroVeiculo();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_cad_veiculoMouseClicked

    private void cad_pontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cad_pontoMouseClicked
        CadastroPontos c = new CadastroPontos();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_cad_pontoMouseClicked

    private void cad_veiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_veiculoActionPerformed
        CadastroVeiculo c = new CadastroVeiculo();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_cad_veiculoActionPerformed

    private void cad_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cad_pontoActionPerformed
        CadastroPontos c = new CadastroPontos();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_cad_pontoActionPerformed

    private void estacionamento_proximoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estacionamento_proximoMouseClicked
        EstacionamentoProximo e = new EstacionamentoProximo();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }//GEN-LAST:event_estacionamento_proximoMouseClicked

    private void estacionamento_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionamento_proximoActionPerformed
        EstacionamentoProximo e = new EstacionamentoProximo();
        e.setLocationRelativeTo(null);
        e.setVisible(true);
    }//GEN-LAST:event_estacionamento_proximoActionPerformed

    private void movimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movimentoActionPerformed
        Movimentacao m = new Movimentacao();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
    }//GEN-LAST:event_movimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cad_ponto;
    private javax.swing.JMenuItem cad_veiculo;
    private javax.swing.JMenuItem estacionamento_proximo;
    private javax.swing.JMenu ferramenta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem movimento;
    // End of variables declaration//GEN-END:variables
}
